export const tasks = [
  {
    id: "t-01",
    name: "Task 1",
    assignee: "Team Member",
    dueDate: "2022-01-01",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "t-02",
    name: "Task 2",
    assignee: "Team Member",
    dueDate: "2022-01-02",
    priority: "Medium",
    status: "In Progress",
  },
  {
    id: "t-03",
    name: "Task 3",
    assignee: "Team Member",
    dueDate: "2022-01-03",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: "t-04",
    name: "Task 4",
    assignee: "Team Member",
    dueDate: "2022-01-04",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "t-05",
    name: "Task 5",
    assignee: "Team Member",
    dueDate: "2022-01-05",
    priority: "Medium",
    status: "In Progress",
  },
  {
    id: "t-06",
    name: "Task 6",
    assignee: "Team Member",
    dueDate: "2022-01-06",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: "t-07",
    name: "Task 7",
    assignee: "Team Member",
    dueDate: "2022-01-07",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "t-08",
    name: "Task 8",
    assignee: "Team Member",
    dueDate: "2022-01-08",
    priority: "Medium",
    status: "In Progress",
  },
  {
    id: "t-09",
    name: "Task 9",
    assignee: "Team Member",
    dueDate: "2022-01-09",
    priority: "Low",
    status: "In Progress",
  },
  {
    id: "t-10",
    name: "Task 10",
    assignee: "Team Member",
    dueDate: "2022-01-10",
    priority: "High",
    status: "In Progress",
  },
  {
    id: "t-11",
    name: "Task 11",
    assignee: "Team Member with a long name that will overflow the table cell",
    dueDate: "2022-01-11",
    priority: "Medium",
    status: "In Progress",
  },
];
